version: "3"
services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/root/.ollama
      - ./scripts:/root/scripts
      - ../src:/root/src:cached
    entrypoint: /root/scripts/start-ollama.sh "mistral,llama2,phi2"
    command: sleep infinity
