version: "3.9"
services:
  autogen:
    user: autogen
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    network_mode: service:localllm
    command: sleep infinity
  localllm:
    user: localllm
    build:
      context: .
      dockerfile: Dockerfile.localllm
      args:
        # entrypoint script arguments below should match this
        # If you change the models, you need to run docker compose with --build to force build
        MODELS: "mistral,llama2"
    # Comment out the following line if you do not have GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Ports should be the same number of ports as the number of models, and start from 8000
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./scripts:/home/localllm/scripts
    entrypoint: /home/localllm/scripts/serve-models.sh "mistral,llama2"
