version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - localllm
    volumes:
      - .:/src
      # So the container does not terminate
    command: tail -f /dev/null
